# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.workers.max=1

## Environment Properties

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.57
neo_version_range=[26.2.0,)
loader_version_range=[6,)

## Mod Properties

mod_id=vault_drawers
mod_name=Vault Drawers
mod_filename=VaultDrawers
mod_license=MIT
mod_version=0.0.0-beta.5
mod_group_id=com.stalkingdragons.minecraft.vaultdrawers
mod_authors=Stalking Dragons
mod_description=Interactive compartment storage for your workshops - NeoForge 26.2 Port

# Mod dependency versions
jei_mc=26.2
jei_version=30.15.0.121
jade_projid=324717
jade_fileid=5591256

## CurseForge Properties
curse_project_id=1668019
modrinth_project_id=
dist_release=release
dist_game_versions=26.2,NeoForge